### ISSUE TITLE
Phone freezes and reboots a few seconds later after screen off.

### ISSUE THREAD

**Issue by ghost** [waylaidwanderer/PowerNapForXposed-Development#1]
Description: Using v0.8, screen off will prevent the screen from turning back on. Charging LED light still works, but buttons won't respond (no vibration when holding down power button). The phone will reboot itself shortly.

Clearing data and cache does not work.
Device: Xperia C3 on stock Lollipop rom

**Comment by waylaidwanderer** [comment]
Try whitelisting "android" and "Google Services Framework" (and maybe "Google Play Services"). A combination of those being whitelisted should hopefully prevent freezes.

Also for others with this issue, please post a logcat up to the reboot if possible.

**Comment by ghost** [comment]
[alogcat.2016-10-23-08-31-16+0800.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/546114/alogcat.2016-10-23-08-31-16.0800.txt)
[alogcat.2016-10-23-08-25-44+0800.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/546115/alogcat.2016-10-23-08-25-44.0800.txt)

I tried capturing them, hope it helps. Btw, Android system/Play Services/Play Framework were whitelisted but it still happens. Turned off for now.

New logcat
[alogcat.2016-10-23-09-14-50+0800.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/546122/alogcat.2016-10-23-09-14-50.0800.txt)
 Turning off endurance mode also gave the same freeze on screen off.

**Comment by enriquezmark36** [comment]
Same problem here with cm 12 and powernap v0.8. When the screen turns off for few seconds, it cannot be turned on again until it reboots and the screen opens again. Unticking both "Endurance Mode" and "Low Battery Mode" doesn't help. 

Logcat until reboot (with markers; I have no idea to get a proper logcat):
[logcat.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/546219/logcat.txt)

/data/anr/traces.txt (suspicious since it was gone after reboot, have to get it after it was created):
[traces.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/546221/traces.txt)

**Comment by Gronkdalonka** [comment]
Same Problem here. Using a rom based on CM12. Whitelisting Android System, Google Frameworks etc. doesen't help. I'm back to v7 for now.

[logcat.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/546401/logcat.txt)

**Comment by waylaidwanderer** [comment]
@enriquezmark36 what phone are you using? I'm beginning to get an idea of what the problem is, but I don't know what is causing it exactly yet.

**Comment by enriquezmark36** [comment]
Samsung Galaxy Core 2 SM-G355H CM 12.1 custom rom.

**Comment by amin-purnawinandar** [comment]
On my case the device rebooted just after enter lockscreen so I cant do anything. 
I tried uninstall PowerNap v0.7 then install PowerNap v0.8 but the problem still occured.
I am using Redmi Note 2 with MIUI 8.0.2.0 and Xposed SolarWarez v86.

I hope i uploaded the correct logcat. This is the only logcat which point to error in your module. 
The logcat tells about StatsHelper.java:40 and WakeLockManager.java:837

[powernap08_logcat.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/546886/powernap08_logcat.txt)

**Comment by ghost** [comment]
Be sure to whitelist SYSTEMUI and your launcher, if on Cyanogenmod white list Trebuchet

**Comment by Gronkdalonka** [comment]
Systemui, launcher (Nova) and anything system related i could find is whitelisted but the problem persists

**Comment by ghost** [comment]
Hmm that's really odd. Are you using any button remappers that may be conflicting some how?

**Comment by ghost** [comment]
If possible test under cm12 nightly if avaliable and see what happens? It may be worth a shot if it works then it's something implimented in the custom rom.

**Comment by Gronkdalonka** [comment]
I'll see if i can manage to test another rom tomorrow

**Comment by enriquezmark36** [comment]
Maybe I'll try too, to revert back to a stock rom backup (touchwiz 4.4) then disable every modules except powernap but doing so will remove nearly every app I have inatalled. Later.

**Comment by ghost** [comment]
I'll be testing on touch wiz 6.0.1 this evening. Good luck to all. Make sure you have the flash able xposed uninstaller just incase things go south

**Comment by firstknightfirst** [comment]
I am having  the same problem. N910c 5.1.1. All was good before the update.

**Comment by ghost** [comment]
I am noticing most of these reports are on AndroidL  (5.x) has anyone tested AndroidM (6.x)?

**Comment by ghost** [comment]
Yeah, 5.1.1 devices are affected, all 6.0 seems to be safe for now.

**Comment by ghost** [comment]
Alright good to know!

**Comment by waylaidwanderer** [comment]
Hi all,

Can you please test this apk and let me know if you still experience reboots? You may need to clear data first, but let me know if it works without clearing it.

[app-release.zip](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/549853/app-release.zip)

**Comment by enriquezmark36** [comment]
Fortunately in 4.4 kitkat (touchwiz), power nap doesn't cause any freezes or what so ever even if the screen is let off for a couple of minutes.

**Comment by Gronkdalonka** [comment]
It's working so far on Android 5.1.1. I didn't wipe any data , just did a "dirty" upgrade

**Comment by waylaidwanderer** [comment]
@Gronkdalonka are statistics showing up?

**Comment by Gronkdalonka** [comment]
Nope, no statistics at all

**Comment by waylaidwanderer** [comment]
@Gronkdalonka Do me a favor and try two things for me. 
1. Clear data and try again. If it works, great.
2. Additionally, try this APK: 
   [app-release.zip](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/549955/app-release.zip)  
   I want to know if this works without causing any reboot issues. If Step 2 works, I'll be using the code for that instead.

**Comment by Gronkdalonka** [comment]
@waylaidwanderer Clearing data made no difference.
Apk from Step 2 is working, no reboots so far but also no statistics. I'll continue fiddling around to see if i can get statistics working.

**Comment by waylaidwanderer** [comment]
Thanks for your help. Could you post the Xposed log here so I can take a look?

**Comment by Gronkdalonka** [comment]
@waylaidwanderer there you go 

[xposed_error_20161025_104129.log.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/550063/xposed_error_20161025_104129.log.txt)

**Comment by waylaidwanderer** [comment]
Can you turn on debug mode (hold down Volume Down key in the home screen of Power Nap) and send me a new log? I'm not sure if the module is actually working because I don't see it allowing any wakelocks in the log. Make sure to turn the screen off for a couple seconds so that Power Nap can do some work before you take a look at the log.

(And when you're done you can turn off debug mode the same way)

**Comment by Gronkdalonka** [comment]
Looks like you were right. Here are the logs 

[error.log.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/550348/error.log.txt)
[error2.log.txt](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/550349/error2.log.txt)

(Before and after reboot, deleted caches in between)

Do you want me to try the first version again ?

**Comment by waylaidwanderer** [comment]
@Gronkdalonka check your Endurance Mode activation settings. You may not have "enable while charging" ticked (which explains the lack of logs), since I assume your phone is plugged in at the moment. It's not a big deal at any rate. The important thing is statistics, and I can't see anything in the logs regarding it. 

Perhaps try clearing data again for the step 2 APK. Don't worry about the first version; doesn't seem like it works anyway.

In the meantime I will attempt some fixes for statistics.

**Comment by waylaidwanderer** [comment]
@Gronkdalonka since the main issue seems to be solved, let's discuss statistics in the relevant issue #2 to reduce clutter.

**Comment by waylaidwanderer** [comment]
I'll close this issue once @AngryManjuu and maybe someone else can confirm.

**Comment by ghost** [comment]
Looks like the issue is fixed, thanks  @waylaidwanderer
