### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ghost** [waylaidwanderer/PowerNapForXposed-Development#13]
Seems around 40ish% battery powernap starts crashing my gui then my system causing a soft reboot
(This also would have been inside of the low battery activation threshold I had set)
Samsung Galaxy S5 G900T
Stock Touch wiz 6.0.1
Arm Based 32 bit processor

**Comment by ghost** [comment]
Might I add it's repetitive

**Comment by waylaidwanderer** [comment]
Duplicate of #8
