### ISSUE TITLE
Message that Power Nap isn't active in xPosed

### ISSUE THREAD

**Issue by martytoo** [waylaidwanderer/PowerNapForXposed-Development#3]
I received this message this morning when opening Power Nap to check if my statistics were visible. When I looked in Xposed it was checked of in Xposed. The message didn't appear when i next checked, but it has showed up again.

It appears when I move back to the main screen after checking my white list. It says:
Xposed Module Not Enabled
Power Nap is currently not enabled in Xposed. Please enable it. 

There is a box to check with a green OK.

Also the statistics aren't working (and I forgot how to change the permissions!).

So after a reboot this was still the case - I had the message about not being enabled. I unchecked Power Nap in Xposed.  I rebooted. I checked Power Nap in Xposed and when rebooting I had more trouble than I ever had with 0.7.  I am now in a weird boot loop situation. I hope I can get to Xposed without going into safe mode.

I will try version 0.7 again to see if that works as it seemed to yesterday.

**Comment by ghost** [comment]
If you cannot escape the boot loop use the exposed uninstaller (assuming you have it) then uninstaller the conflicting modules and reflash xposed.

**Comment by martytoo** [comment]
Thanks.  I was able to access xposed and turned off Power Nap.  I plan to reinstall version 0.7 to see if this ROM is ok with it.

**Comment by ghost** [comment]
May I ask what rom you are on. I have yet to test it out on stock Samsung android 6.0.1 For the S5 I plan to later today.

**Comment by martytoo** [comment]
The ROM that I installed a few months ago on my Verizon S5 is labeled:

G900V_OA8_Stock_KERNEL_SafeStrap-Flashable.zip

It is a version of the stock ROM which can be flashed without losing root.  

0.7 hasn't caused any freezing today.

**Comment by waylaidwanderer** [comment]
@martytoo let me know if [this APK](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/549853/app-release.zip) fixes your issue. (It's in a zip file due to GitHub uploading restrictions)

**Comment by ghost** [comment]
The rom you are on is a flash able version of the stock 6.0.1 update since there is no current way around that models bootloader (unlike on the G900T which I have) you use safe strap to run custom roms, that rom is just a prerooted stock rom.

**Comment by martytoo** [comment]
This fixed the boot loop issue.  I will give you more feedback after using
it today.  Thanks.

**Comment by martytoo** [comment]
Yes, you are correct except it is a version of 5.0 that allows root, not
6.0.1.  I haven't had the time to do version 6 which wasn't available that
I could see when I upgraded to Lollipop.

On Oct 25, 2016 8:35 AM, "GreezyJR" notifications@github.com wrote:

The rom you are on is a flash able version of the stock 6.0.1 update since
there is no current way around that models bootloader (unlike on the G900T
which I have) you use safe strap to run custom roms, that rom is just a
prerooted stock rom.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/waylaidwanderer/PowerNapForXposed-Development/issues/3#issuecomment-256022157,
or mute the thread

**Comment by waylaidwanderer** [comment]
@martytoo Glad to hear it. Post feedback in #1
