### ISSUE TITLE
Phone Freezes and Doesn't turn on screen when receiving a call

### ISSUE THREAD

**Issue by Weeka89** [waylaidwanderer/PowerNapForXposed-Development#5]
Running One Plus 3 stock OOS 3.2.7 rooted with elemental x kernell.
- Whitelisted every single system service and still i'm facing a problem that when i receive a call while the screen is off the phone keeps ringing infinitely and freezes, only way to fix it is a hard reboot. maybe it's linked somehow to the reported issue of phone freezing when unlocking.

**Comment by waylaidwanderer** [comment]
Pretty sure this is the same issue as #1.
