### ISSUE TITLE
Statistics cannot be cleaned Even if it is delete manually. 

### ISSUE THREAD

**Issue by Moderndaycowboy** [waylaidwanderer/PowerNapForXposed-Development#6]
Even if I cleared statistics, I lock the phone and when I unlocked, old statistics is shown by the app.
Please fix it.

**Comment by waylaidwanderer** [comment]
Try this apk - [app-release.zip](https://github.com/waylaidwanderer/PowerNapForXposed-Development/files/550425/app-release.zip)

Make sure you clear data first before installing.

**Comment by Moderndaycowboy** [comment]
I installed, İt didn't work, I clear statistics but when i unlocked my phone nothing changes. This is only cleared when i rebooted.

**Comment by waylaidwanderer** [comment]
Can you upload the Xposed log and the logcat for when you click the button to clear statistics?
