### ISSUE TITLE
Power nap crashes on low battery mode

### ISSUE THREAD

**Issue by billwang115** [waylaidwanderer/PowerNapForXposed-Development#8]
On my 4.4.2 stock rom, everytime low battery mode auto activates, it keeps displaying the message "Powernap has stopped". I think some other users running kitkat also have this problem.

**Comment by ghost** [comment]
Your power saver may consider powernap as not needed and may be disabling it when it is not open.

**Comment by billwang115** [comment]
@GreezyJR The thing is, my phone does not come with a battery saver. As well, the low battery mode for powernap worked in 0.7.

**Comment by waylaidwanderer** [comment]
This is fully fixed for the next release now.
